[workspace]
members = [
    "dns",
    "floodsub",
    "identify",
    "kad",
    "libp2p",
    "ping",
    "ratelimit",
    "relay",
    "secio",
    "core",
    "muxers/mplex",
    "muxers/yamux",
    "utils/circular-buffer",
    "utils/multiaddr",
    "utils/multihash",
    "utils/multistream-select",
    "utils/rw-stream-sink",
    "utils/peerstore",
    "utils/datastore",
    "utils/transport-timeout",
    "transports/tcp",
    "transports/uds",
    "transports/websocket",
]
