[workspace]
members = [
    "libp2p",
    "core",
    "core/multiaddr",
    "core/multihash",
    "core/multistream-select",
    "core/rw-stream-sink",
    "protocols/dns",
    "protocols/floodsub",
    "protocols/identify",
    "protocols/kad",
    "protocols/ping",
    "protocols/relay",
    "protocols/secio",
    "muxers/mplex",
    "muxers/yamux",
    "utils/peerstore",
    "utils/datastore",
    "transports/tcp",
    "transports/uds",
    "transports/websocket",
    "transports/timeout",
    "transports/ratelimit",
]
