[workspace]
members = [
    "libp2p",
    "core",
    "protocols/dns",
    "protocols/floodsub",
    "protocols/identify",
    "protocols/kad",
    "protocols/ping",
    "protocols/relay",
    "protocols/secio",
    "muxers/mplex",
    "muxers/yamux",
    "utils/circular-buffer",
    "utils/multiaddr",
    "utils/multihash",
    "utils/multistream-select",
    "utils/rw-stream-sink",
    "utils/peerstore",
    "utils/datastore",
    "utils/transport-timeout",
    "utils/ratelimit",
    "transports/tcp",
    "transports/uds",
    "transports/websocket",
]
